name: Mention technical debt PR

on:
  issue_comment:
  pull_request_review_comment:
    types:
      - created

jobs:
  fetch_data_from_issue:
    runs-on: ubuntu-latest
    outputs:
      COMMENT_BODY: ${{ steps.set-output.outputs.COMMENT_BODY }}
      OWNER: ${{ steps.set-output.outputs.OWNER }}
      PR_NUMBER: ${{ steps.set-output.outputs.PR_NUMBER }}
      PR_URL: ${{ steps.set-output.outputs.PR_URL }}
      REPOSITORY: ${{ steps.set-output.outputs.REPOSITORY }}
    steps:
      - id: set-output
        name: Set output
        run: |
          echo "::set-output name=COMMENT_BODY::${{ github.event.comment.body }}"
          echo "::set-output name=OWNER::${{ github.event.repository.owner.login }}"
          echo "::set-output name=PR_NUMBER::${{ github.event.issue.number }}"
          echo "::set-output name=PR_URL::${{ github.event.issue.pull_request.html_url }}"
          echo "::set-output name=REPOSITORY::${{ github.event.repository.name }}"

  has_triggered:
    name: Fetch data
    runs-on: ubuntu-latest
    needs: fetch_data_from_issue
    outputs:
      triggered: ${{ steps.detect-trigger.outputs.result }}
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(needs.fetch_data_from_issue) }}
        run: |
          echo $EVENT_CONTEXT
  fetch_issue_number:
    name: Fetch issue number from comment
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.ensure-issue-number.outputs.result }}
    steps:
      - id: ensure-issue-number
        if: steps.has-tech-debt-tag.outputs.triggered == 'true'
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const { COMMENT_BODY, OWNER, REPOSITORY, PR_URL, PR_NUMBER } = process.env;
            const techDebtTag = COMMENT_BODY.match(/\#tech-debt: *#[1-9]+/g)[0];
            const issueNumber = techDebtTag.match(/\#[1-9]+/g)[0].substring(1);
            const issue = await github.rest.issues.get({
              owner: OWNER,
              repo: REPOSITORY,
              issue_number: issueNumber,
            });

            if (!issue) {
              console.log(`Cannot find issue ${issueNumber}, please tag the right issue.`);
              return;
            }

            if (issue.data.pull_request) {
              console.log(`Cannot tag another pull request as the technical debt, please tag the right issue.`);
              return;
            }

            return issueNumber;
  create_comment:
    name: Create comment
    runs-on: ubuntu-latest
    needs: fetch_issue_number
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - uses: actions/github-script@v5
        env:
          OWNER: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          PR_URL: ${{ github.event.issue.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.issue.number }}
        with:
          script: |
            const { OWNER, REPOSITORY, PR_URL, PR_NUMBER } = process.env;

            github.rest.issues.createComment({
              issue_number: ${{ needs.fetch_issue.outputs.issue-number }},
              owner: OWNER,
              repo: REPOSITORY,
              body: `This technical debt has been tagged in the [PR#${PR_NUMBER} ](\${PR_URL}).`
            });
