name: Mention technical debt PR

on:
  issue_comment:
  pull_request_review_comment:
    types:
      - created

jobs:
  fetch_data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  fetch_issue:
    name: Fetch issue
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.ensure-issue-number.outputs.result }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: has-tech-debt-tag
        with:
          trigger: '#tech-debt:'

      - name: ensure-issue-number
        if: steps.has-tech-debt-tag.outputs.triggered == 'true'
        uses: actions/github-script@v5
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          PR_URL: ${{ github.event.issue.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.issue.number }}
        with:
          result-encoding: string
          script: |
            const { COMMENT_BODY, OWNER, REPOSITORY, PR_URL, PR_NUMBER } = process.env;
            const techDebtTag = COMMENT_BODY.match(/\#tech-debt: *#[1-9]+/g)[0];
            const issueNumber = techDebtTag.match(/\#[1-9]+/g)[0].substring(1);
            const issue = await github.rest.issues.get({
              owner: OWNER,
              repo: REPOSITORY,
              issue_number: issueNumber,
            });

            if (!issue) {
              console.log(`Cannot find issue ${issueNumber}, please tag the right issue.`);
              return;
            }

            if (issue.data.pull_request) {
              console.log(`Cannot tag another pull request as the technical debt, please tag the right issue.`);
              return;
            }

            return issueNumber;
      - run: echo "${{steps.ensure-issue-number.outputs}}"
  create_comment:
    name: Create comment
    runs-on: ubuntu-latest
    needs: fetch_issue
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(needs.fetch_issue) }}
        run: |
          echo $EVENT_CONTEXT
      - uses: peter-evans/create-or-update-comment@v1.4.5
        env:
          PR_URL: ${{ github.event.issue.pull-request.html_url }}
          PR_NUMBER: ${{ github.event.issue.number }}
        with:
          issue-number: ${{ needs.fetch_issue.outputs.issue-number }}
          body: |
            This technical debt has been tagged in the [PR#$PR_NUMBER]($PR_URL)
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
