name: PR technical debts reference

on:
  issue_comment:
    types:
      - created

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '#tech-debt:'
      - uses: actions/github-script@v5
        with:
          script: |
            console.log(github.event);
        if: steps.check.outputs.triggered == 'true'

